### ISSUE TITLE
Shopping cart should handle errors on cart update event

### ISSUE THREAD

**Issue by reho** [PrestaShop/ps_shoppingcart#23]
When an error occured during product add to cart, we need to show the error messages.
As I use this module it doesn't seem to handle if the updateCart event.resp.hasError == true.

I made some extensions handling these situation. Do you plan some similar functionality or should I fork it and send my mods?

**Comment by jf-viguier** [comment]
Hi @reho,
I'm facing the same issue. Did you find a way to fix it ?

**Comment by reho** [comment]
> Hi @reho,
> I'm facing the same issue. Did you find a way to fix it ?

Hi,

As i checked my old solution I found in my svn a solution and i found it when i deleted the solution after 6 months of usage. I don't know why i didn't used it anymore, maybe it is fixed in a later version? 

So the solution in nutshell:
- modified the ps_shoppingcart\controllers\front\ajax.php by adding a new action 'show-error'
- modified the ps_shoppingcart\ps_shoppingcart.js checking if the event.resp.hasError == true, and calling the ajax with the new action 'show-error' instead of the normal event.reason.linkAction
- this new action sends back the error modal

**Comment by jf-viguier** [comment]
Thanks I've found your PR and I've made mine too.

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/ps_shoppingcart/pull/41/
